package Entities;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Inquerito implements Serializable {

    @Basic
    private String tituloInquerito;

    @Basic
    private String dataFim;

    @Basic
    private String dataInicio;

    @Column(unique = true)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long idInquerito;

    public Inquerito() {

    }

    public String getTituloInquerito() {
        return this.tituloInquerito;
    }

    public void setTituloInquerito(String tituloInquerito) {
        this.tituloInquerito = tituloInquerito;
    }

    public String getDataFim() {
        return this.dataFim;
    }

    public void setDataFim(String dataFim) {
        this.dataFim = dataFim;
    }

    public String getDataInicio() {
        return this.dataInicio;
    }

    public void setDataInicio(String dataInicio) {
        this.dataInicio = dataInicio;
    }

    public Long getIdInquerito() {
        return this.idInquerito;
    }

    public void setIdInquerito(Long idInquerito) {
        this.idInquerito = idInquerito;
    }
}
