package Entities;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

@Entity
public class RespInquerito implements Serializable {

    @ManyToOne(targetEntity = Resposta.class)
    private Resposta resposta;

    @Column(unique = true)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long idRespInquerito;

    @ManyToOne(targetEntity = UtilizadorInquerito.class)
    private UtilizadorInquerito utilizadorInquerito;

    public RespInquerito() {

    }

    public Resposta getResposta() {
        return this.resposta;
    }

    public void setResposta(Resposta resposta) {
        this.resposta = resposta;
    }

    public Long getIdRespInquerito() {
        return this.idRespInquerito;
    }

    public void setIdRespInquerito(Long idRespInquerito) {
        this.idRespInquerito = idRespInquerito;
    }

    public UtilizadorInquerito getUtilizadorInquerito() {
        return this.utilizadorInquerito;
    }

    public void setUtilizadorInquerito(UtilizadorInquerito utilizadorInquerito) {
        this.utilizadorInquerito = utilizadorInquerito;
    }
}
