package Entities;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

@Entity
public class Resposta implements Serializable {

    @Column(unique = true)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long idResposta;

    @Basic
    private String texto;

    @ManyToOne(targetEntity = Pergunta.class)
    private Pergunta pergunta;

    @Basic
    private String respCerta;

    public Resposta() {

    }

    public Long getIdResposta() {
        return this.idResposta;
    }

    public void setIdResposta(Long idResposta) {
        this.idResposta = idResposta;
    }

    public String getTexto() {
        return this.texto;
    }

    public void setTexto(String texto) {
        this.texto = texto;
    }

    public Pergunta getPergunta() {
        return this.pergunta;
    }

    public void setPergunta(Pergunta pergunta) {
        this.pergunta = pergunta;
    }

    public String getRespCerta() {
        return this.respCerta;
    }

    public void setRespCerta(String respCerta) {
        this.respCerta = respCerta;
    }
}
